services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=dbpassword'
      - 'POSTGRES_USER=dbuser'
    ports:
      - '5432'
   

  java:    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
    depends_on:
      - postgres  
        