services:
  postgres:
    image: 'postgres:12.15-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=dbpassword'
      - 'POSTGRES_USER=dbuser'
    ports:
      - '5432:5432'
    volumes:
      - './database:/var/lib/postgresql/data'

  java:    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
    depends_on:
      - postgres  
        