INSERT INTO tb_category (name) VALUES
                                   ('Eletrônicos'),
                                   ('Eletrodomésticos'),
                                   ('Móveis'),
                                   ('Vestuário'),
                                   ('Calçados'),
                                   ('Alimentos e Bebidas'),
                                   ('Esportes e Lazer'),
                                   ('Livros e Papelaria'),
                                   ('Brinquedos'),
                                   ('Beleza e Cuidados Pessoais'),
                                   ('Ferramentas e Construção'),
                                   ('Automotivo'),
                                   ('Pet Shop'),
                                   ('Informática'),
                                   ('Saúde e Bem-Estar'),
                                   ('Joias e Acessórios'),
                                   ('Games'),
                                   ('Artigos de Festa'),
                                   ('Casa e Decoração'),
                                   ('Instrumentos Musicais');